#!/bin/bash
# Her SessionStart'ta çalışır: current Claude Code project dir'i için
# mempalace.yaml yoksa yaratır (temiz wing adı + subagents ignore + stack-aware rooms).
#
# Claude Code session cache path: ~/.claude/projects/<cwd-slashes-to-dashes>/
# Proje dir yoksa yaratır (mkdir -p) → ilk oturumda bile yaml garantili.

set -e

CWD="${PWD}"
CWD_ENCODED=$(echo "$CWD" | sed 's|/|-|g')
PROJECT_DIR="$HOME/.claude/projects/$CWD_ENCODED"
YAML="$PROJECT_DIR/mempalace.yaml"

# Yaml zaten varsa atla
[ -f "$YAML" ] && exit 0

# Project dir yoksa oluştur (Claude Code sonra buraya yazacak)
mkdir -p "$PROJECT_DIR"

# Wing adı: cwd basename (lowercase, güvenli slug)
WING=$(basename "$CWD" | tr '[:upper:]' '[:lower:]' | tr -c 'a-z0-9-' '-' | sed 's/--*/-/g; s/^-//; s/-$//')
[ -z "$WING" ] && WING="default"

# Stack tespiti — proje tipine göre ekstra room'lar
EXTRA_ROOMS=""
if [ -f "$CWD/pyproject.toml" ] || [ -f "$CWD/requirements.txt" ]; then
  [ -f "$CWD/manage.py" ] && STACK="django" || STACK="python"
elif [ -f "$CWD/package.json" ]; then
  if grep -q '"next"' "$CWD/package.json" 2>/dev/null; then STACK="nextjs"
  elif grep -q '"svelte"' "$CWD/package.json" 2>/dev/null; then STACK="svelte"
  elif grep -q '"react"' "$CWD/package.json" 2>/dev/null; then STACK="react"
  else STACK="node"
  fi
elif [ -f "$CWD/Cargo.toml" ]; then
  [ -d "$CWD/src-tauri" ] && STACK="tauri" || STACK="rust"
elif [ -f "$CWD/go.mod" ]; then
  STACK="go"
elif [ -f "$CWD/pubspec.yaml" ]; then
  STACK="flutter"
else
  STACK="generic"
fi

# Stack'e göre özel room listesi
case "$STACK" in
  django)   STACK_ROOMS="models views urls templates migrations settings tests";;
  python)   STACK_ROOMS="modules tests scripts";;
  nextjs)   STACK_ROOMS="pages app components api styles";;
  svelte)   STACK_ROOMS="routes components stores lib";;
  react)    STACK_ROOMS="components hooks pages services";;
  node)     STACK_ROOMS="src tests scripts";;
  rust|tauri) STACK_ROOMS="src tests examples";;
  go)       STACK_ROOMS="cmd internal pkg tests";;
  flutter)  STACK_ROOMS="lib screens widgets services";;
  *)        STACK_ROOMS="";;
esac

{
  echo "# Auto-generated by personal-assistant plugin"
  echo "# Wing: proje spesifik mempalace wing adı (wake-up bu wing'i scope eder)"
  echo "# Detected stack: $STACK"
  echo "wing: $WING"
  echo "stack: $STACK"
  echo "rooms:"
  echo "  - name: conversations"
  echo "    description: Claude Code session transcripts"
  echo "    keywords: [conversation, chat, session]"
  echo "  - name: decisions"
  echo "    description: Architectural decisions, trade-offs, rationale"
  echo "    keywords: [decision, karar, trade-off, neden]"
  echo "  - name: setup"
  echo "    description: Installation, configuration, env"
  echo "    keywords: [setup, install, config, env, deploy]"
  for r in $STACK_ROOMS; do
    echo "  - name: $r"
    echo "    keywords: [$r]"
  done
  echo "  - name: general"
  echo "    description: Other files"
  echo "    keywords: []"
  echo "ignore:"
  echo "  - \"subagents/\""
  echo "  - \"*.meta.json\""
  echo "  - \"agent-*.jsonl\""
  echo "  - \".venv/\""
  echo "  - \"node_modules/\""
  echo "  - \"target/\""
  echo "  - \"dist/\""
  echo "  - \"build/\""
  echo "  - \"__pycache__/\""
} > "$YAML"

exit 0
